# 头部菜单，title: link
menu:
  About: /about
  Github: https://github.com/zhangqiang821
#  Twitter: https://twitter.com/zhangqiang

# 是否显示目录
TOC: true

# 是否自动播放音乐
autoplay: false

# 默认音乐
mp3:
  - http://link.hhtjim.com/163/5146554.mp3
  - http://link.hhtjim.com/qq/001faIUs4M2zna.mp3

# 首页封面图, 为空时取文章的cover作为封面
welcome_cover: # /img/welcome-cover.jpg

# 默认文章封面图
cover: /img/cover.jpg

# 是否关闭默认滚动条
scrollbar: true

# Gitalk 评论插件（https://github.com/gitalk/gitalk）
gitalk:
  # 是否自动展开评论框
  autoExpand: true
  # 应用编号
  clientID: 08954cc66293d328923e
  # 应用秘钥
  clientSecret: f6350fd92628d20126572169dc7379945e81ea84
  # issue仓库名
  repo: zhangqiang.github.io
  # Github名
  owner: zhangqiang
  # Github名
  admin: [zhangqiang]
  # Ensure uniqueness and length less than 50
  id: location.pathname
  # Facebook-like distraction free mode
  distractionFreeMode: false

# 网站关键字
keywords: cc

# 要使用google_analytics进行统计的话，这里需要配置ID
google_analytics:

# 网站ico
favicon: /img/favicon.png

# rss文件
rss: atom.xml
#  新建文章模板
#---
#title: My awesome title
#date: 2016-10-12 18:38:45
#tags:
#- 标签
#- 标签
#mp3: http://domain.com/awesome.mp3
#cover: http://domain.com/awesome.jpg
#---
